// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AboutSection: typeof import('./components/AboutSection.vue')['default']
    ClientsSection: typeof import('./components/ClientsSection.vue')['default']
    HomePageSection: typeof import('./components/atoms/HomePageSection.vue')['default']
    ProjectsSection: typeof import('./components/molecules/ProjectsSection/ProjectsSection.vue')['default']
    SocialsSection: typeof import('./components/SocialsSection.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheHeroArea: typeof import('./components/TheHeroArea.vue')['default']
    TheTopBar: typeof import('./components/TheTopBar.vue')['default']
  }
}

export { }
